### ISSUE TITLE
3.x CakePHP Schema plugin

### ISSUE THREAD

**Issue by Laykou** [FriendsOfCake/awesome-cakephp#104]
Hey,

I've created the Cake 3.x Schema plugin https://github.com/Laykou/cakephp-schema
There is a place for improvement but I just wanted to let you know.

It allows you to save the schema to the PHP file and loads it (into different database e.g.). It also supports seeding the data which is very usefull for testing (specially user acceptacne testing, where you want to simulate the application with real data).

**Comment by jadb** [comment]
@Laykou, do you mind adding it to the list and submitting a PR?

**Comment by dereuromark** [comment]
Adding a few tests wouldn't hurt, though :)

**Comment by jadb** [comment]
I agree with @dereuromark for the plugin's quality but also promoting it on the list could help others contribute tests for it. I am closing this as an issue and waiting for your PR @Laykou.
