### ISSUE TITLE
More details

### ISSUE THREAD

**Issue by bobmulder** [FriendsOfCake/awesome-cakephp#138]
Hi guys,

I like this list of plugins, and I love to search through them. However, I would like to have more details about a plugin. Just the name is enough, but for example I would like to know what organisation/user created it, how much stars the plugin has, and how many downloads on packagist. 

I got the following idea: Why not converting all lists (per category) to tables with the following structure:

| Plugin    	| Description                                      	| Owner       	| Stars 	| Downloads 	|
|-----------	|--------------------------------------------------	|-------------	|-------	|-----------	|
| Cakephp   	| Amazing one :)                                   	| CakePHP     	| 16.000|123.234|
| CakeAdmin 	| Dynamic Admin Panel for your CakePHP Application 	| CakeManager 	|  1000   	|           	12.234|
| Crud      	| CakePHP Application development on steroids      	|  FriendsOfCake  | 2000   	|   23.234        	|

*I wanted to add shields via shields.io, but it seems to be down...*

I think this structure will make it easier to find what you want, and provide you a better result of available plugins.

**Comment by jadb** [comment]
There is http://plugins.cakephp.org which aggregates data from Github and other sites; this list is not dynamic.

**Comment by bravo-kernel** [comment]
Why am I getting deja-vu feelings :trollface:

**Comment by bobmulder** [comment]
How is this list not dynamic? I only want to make this a better view...

**Comment by jadb** [comment]
Sorry maybe I didn't explain correctly. Markdown is static, having those numbers in the list is unmaintainable. Furthermore, this list follows every other awesome list look/flow. 

The 2 problems I see:
- List should not be different from all other awesome lists
- And if it were to be, who would update the star count every time a project gets a new start?

Here's what @bravo-kernel was referring to: https://github.com/FriendsOfCake/awesome-cakephp/pull/121#issuecomment-125876392

**Comment by dereuromark** [comment]
Exactly, if anything the plugins.cakephp.org should be enhanced here as a dynamic website that can handle these things.

**Comment by bobmulder** [comment]
@jadb I agree with the point that it shouldn't be different than other awesome lists. (however, who tells us not to do it? ;))

And about updating stars and downloads: For that we have shields.io: http://shields.io/

[![GitHub stars](https://img.shields.io/github/stars/badges/shields.svg?style=social&label=Star)]()

With shields.io we are able to dynamically show stars, downloads (packagist) and go on. Adding those details will make it easier to sort plugins for yourself...
