### ISSUE TITLE
Cake3 Sitemap plugin

### ISSUE THREAD

**Issue by Adnan0703** [FriendsOfCake/awesome-cakephp#140]
I would like to submit my plugin to the list for Cake3.

https://github.com/Adnan0703/sitemap

It doesn't have tests. I would have written tests, but I couldn't figure out how to write tests for this plugin.

**Comment by dereuromark** [comment]
Tests and documentation seem to be missing.

**Comment by Adnan0703** [comment]
@dereuromark It has documentation. If you have a look at it and give me some idea how to write test for it, I'll write tests.

**Comment by dereuromark** [comment]
Sry, you are right.
Well, no objections from me then.

**Comment by jadb** [comment]
@Adnan0703 leaving this open, ping us when you have the tests :smiley:

**Comment by ADmad** [comment]
Your readme says:

> Also it iterates over table records instead of retrieving all records at once.

But [here](https://github.com/Adnan0703/sitemap/blob/master/src/Iterator/ModelIterator.php#L83) `$query->toArray()` is done which would fetch and stored all records in memory as array. 

Doesn't that defeat the point of record iteration?

**Comment by Adnan0703** [comment]
@ADmad  `$query->toArray()` won't fetch all records there. You can limit the number of records it will fetch using config. It works like pagination.
I think it's better to query db 10 times and fetch 100 records each time instead of query db 1000 and fetch 1 record each time from a table with 1000 records.

**Comment by ADmad** [comment]
I know how pagination works :)  My point is your statement about iterating over table records is misleading. It suggests that only one record is fetched and stored in memory which is not the case.

**Comment by Adnan0703** [comment]
@ADmad what do you suggest I should write there?

**Comment by Adnan0703** [comment]
@jadb added a test. Let me know where to improve it more. :)

**Comment by jadb** [comment]
@Adnan0703 this is starting to look good :+1:

**Comment by dereuromark** [comment]
Closing for now, you can open a PR when everything is ready.
