### ISSUE TITLE
Suggestion: remove non-upgraded repos

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/awesome-cakephp#152]
May I suggest removing the strike-through repos now that Cake 3 has been out for some time.

**Comment by dereuromark** [comment]
The idea of those is still the same: Provide easy reference to the old ones and make it easier to help upgrading them instead of reinventing the wheel. 
My opinion still stands: Valuable meta data otherwise lost.

**Comment by bravo-kernel** [comment]
If not black and white let's at least sensibly curate the strike-through items, some entries are like needle-to-eye:

- [Books section] is all about 2.x
- [AmazonSdk plugin](https://github.com/mcallisto) repo does not even exist anymore

Not hurting anything is ofcourse purely subjective, for me it makes our list looks less crisp compared to the others.

**Comment by dereuromark** [comment]
Sure

**Comment by ADmad** [comment]
@bravo-kernel I had suggested a earlier too in #121 but as you can see @dereuromark wants to keep them.

**Comment by dereuromark** [comment]
@bravo-kernel I think our lists are still 1000x better than the awesome-php on or similar ones, because ours are actually well maintained. I think that outweighs any of those issues.
But yeah, please lets remove all outdated ones for sure.

**Comment by ADmad** [comment]
> But yeah, please lets remove all outdated ones for sure.

Yay!  @bravo-kernel Would you like to do the honors?

**Comment by dakota** [comment]
Could we perhaps move them into their own subheading ? That way we don't
loose the knowledge, but they no longer clutter the list?

**Comment by dereuromark** [comment]
Then we can remove them alltogether and maybe make a WIKI page containing the TODOs?

**Comment by dakota** [comment]
:+1: for the wiki page.

**Comment by dereuromark** [comment]
Added a wiki start entry. Someone just has to move them over now:
https://github.com/FriendsOfCake/awesome-cakephp/wiki#plugins-not-yet-upgraded-from-2x-to-3x

**Comment by bravo-kernel** [comment]
Awesome (no pun intended), I hereby volunteer to move things over. Will probably not be done before the weekend though.

**Comment by bravo-kernel** [comment]
Steps:
- [x] move all non-upgraded material as-is to [wiki](https://github.com/FriendsOfCake/awesome-cakephp/wiki)
- [ ] remove dead links from wiki
- [ ] remove moved items from the main list
- [ ] curate main list (order, etc)
- [ ] follow-up status questions on the non-upgraded repos (**?!?**)

Things noticed in the wiki so far:
- is @dereuromark migration plugin not upgraded yet?
- is croogo not upgraded yet?

**Comment by dereuromark** [comment]
@bravo-kernel What migration plugin? You can contact me in IRC.
