### ISSUE TITLE
A new plugin

### ISSUE THREAD

**Issue by clthck** [FriendsOfCake/awesome-cakephp#177]
Can you add [cakephp-jade](https://github.com/clthck/cakephp-jade) into Templating category?

**Comment by clthck** [comment]
Hello @dereuromark , can you tell me why this plugin is not eligible to be added to `awesome-cakephp`?

**Comment by dereuromark** [comment]
I am sorry, that must have happened by mistake.

Looks good.
But a few tests wouldn't hurt, to show people it works as expected.

**Comment by clthck** [comment]
I'm pretty new to writing tests, but people can try the plugin. In fact, I've been using it for several real-world projects and it's been working without hassle.

**Comment by dereuromark** [comment]
Give it a try.
You can also look at the existing plugins, and how they set up tests.
It really is super fast, and worth it (auto testing for all PHP versions etc via Travis CI).

**Comment by dereuromark** [comment]
PS: `clthck\JadeView` The convention is to use uppercase CamelCases: `Clthck\JadeView`. This avoids typos usually.

**Comment by clthck** [comment]
I added test suites to the plugin. And also changed namespace from `clthck\JadeView` to simply `JadeView`. Can you check it and add to the list now?

**Comment by dereuromark** [comment]
Your travis link is pointing to the svg image, not the actual site ;)
But looks great otherwise, nice job!
Please make a PR to add your new plugin in the templating section.

**Comment by clthck** [comment]
ok

**Comment by clthck** [comment]
Can you teach me how to make a PR? because I've never done PR before.

**Comment by dereuromark** [comment]
You go to the README of this file, go on EDIT it and modify it accordingly. Then you click on COMMIT and make a PR this way.

**Comment by clthck** [comment]
Ok. Just made a pull request.

**Comment by dereuromark** [comment]
Resolved with https://github.com/FriendsOfCake/awesome-cakephp/pull/178
