### ISSUE TITLE
remove FriendsOfCake/Authenticate plugin 

### ISSUE THREAD

**Issue by makamo** [FriendsOfCake/awesome-cakephp#217]
Is no longer support and composer give error when try to install 
`Package friendsofcake/authenticate is abandoned, you should avoid using it. No replacement was suggested.
`

**Comment by ADmad** [comment]
It can't be "removed" as that would break existing apps already using it.

**Comment by jippi** [comment]
@ADmad removing it from the README here would not break anything?

**Comment by dereuromark** [comment]
I can move it to "Dead section"

**Comment by ADmad** [comment]
I am a dumbass! I earlier checked on mobile and didn't notice this issue is for the "awesome-cakephp".

So :+1: for removing it from the list. @dereuromark I don't think keeping it under "Dead" section is also necessary.

**Comment by dereuromark** [comment]
Doesn't hurt to mention it there.
Moved to https://github.com/FriendsOfCake/awesome-cakephp/wiki/RIP
Thank you :)
