### ISSUE TITLE
Assets, my plugin

### ISSUE THREAD

**Issue by mirko-pagliai** [FriendsOfCake/awesome-cakephp#224]
[This](https://github.com/mirko-pagliai/assets) is my `Assets` plugin.
It uses matthiasmullie/minify and provides a convenient helper to generate and link assets files.

You can see the `readme` file for more infos.

**Comment by ADmad** [comment]
How is this better / different than Mark Story's AssetCompress?

**Comment by mirko-pagliai** [comment]
I don't like `AssetCompress`, because it needs configuration, build files and filters configuration. They are too many stuffs to maintain.

So I wrote a plugin that only needs to use the `AssetsHelper` instead of `HtmlHelper`.
In other words, in the templates it is sufficient to use `AssetsHelper::css()` instead of `HtmlHelper::css()` and the same for the `script()` method.

**Comment by dereuromark** [comment]
The main idea behind those configuration and build files is that those things do not (and should not happen) dynamically, but pre-built during deployment (e.g. via shell).
Yours seems to be a bit less powerful in those regards, and the AssetCompress plugin not without reason is the de-facto standard tool here used throughout the cakephp world right now.

I do not want to say your's isn't awesome, it probably has its own strengths.
So we just want to clarify the reasons why it would fit here on the list.

**Comment by mirko-pagliai** [comment]
Yes, yes, Probably I have explained badly. I absolutely did not say that AssetCompress is a plugin that I think is not working well (otherwise I would have proposed a change to that plugin, not writing a new one).

Quite simply I have found it useful to do these things dynamically and not necessarily during deployment, because in my projects is so.

This is the reason :-) so, this is a plugin that handles automatically and dynamically asset files, this is the difference

**Comment by markstory** [comment]
I think having 2 different plugins with different approaches is good. There is more than one way to do asset building :smile:

**Comment by mirko-pagliai** [comment]
Thanks @markstory.

I forgot to say: my plugin automatically detects if assets have changed and combines and minifies them again. Otherwise it works as if they were in cache.
This does not consume many resources, because the plugin simply considers the time of last modification of the assets.

Now I can not remember if AssetCompress also does this.

**Comment by markstory** [comment]
> Now I can not remember if AssetCompress also does this.

It does. It can also walk through dependency trees for sass/less/sprockets and check those files too.

**Comment by dereuromark** [comment]
Closing until a PR has been opened as suggested.
