### ISSUE TITLE
CoolOps Web Application Skeleton based on CakePHP 3 and MaterializeCSS

### ISSUE THREAD

**Issue by wawanabnan** [FriendsOfCake/awesome-cakephp#227]
Hi,

I am confused what is CoolOps Web Application Skeleton based on CakePHP 3 and MaterializeCSS repository for? What is different with the official cakephp3 repo?

The repo is mentioned that it is CakePHP material ui admin template project, but where ui-admin the template?

thank

**Comment by dereuromark** [comment]
It is just an optional "layout-rich" base template app to use instead of the core one. Please ask them any of those specific questions. Out of scope here.

**Comment by wawanabnan** [comment]
ya, but they have no contact. That's why? Thank anyway.
