### ISSUE TITLE
Integración SendGrid

### ISSUE THREAD

**Issue by Oxicode** [FriendsOfCake/awesome-cakephp#250]
Cakephp 3.4 
Sendgrid api v3
https://github.com/oxicode/cakephp-sendgrid

**Comment by dereuromark** [comment]
You have a typo in 

    require oxicode/cakephp-Sendgrid

the casing is important usually (S vs s)

also, some tests might be good for this plugin to avoid regression in the future.

**Comment by dereuromark** [comment]
Please open up a PR instead :)
