### ISSUE TITLE
RFC: Add CakePHP based apps to the list

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/awesome-cakephp#278]
Can we add another section? CakePHP based open source apps?

Today I found https://github.com/humhub/humhub and sadly realized there is no popular CakePHP open source app I'm aware of except Croogo. And even Croogo just has a fraction of the stars Humhub has, which is Yii2 based.

**Comment by dereuromark** [comment]
Sure, somewhere along https://github.com/FriendsOfCake/awesome-cakephp#cms-and-applications-built-on-cakephp ?
What would that category/section be?

**Comment by burzum** [comment]
Ah OK, I haven't seen this section for some reason when I checked the list before. :(
