### ISSUE TITLE
How to I suggest new plugin to list?

### ISSUE THREAD

**Issue by ribafs** [FriendsOfCake/awesome-cakephp#297]
I could not create a new one Pull Request then I create this Issue.
I create some plugins to CakePHP 3.
I want to add to this ist:

https://github.com/ribafs/cake-control-br
https://github.com/ribafs/twbs-cake-css
https://github.com/ribafs/cake-control
https://github.com/ribafs/control-default

**Comment by dereuromark** [comment]
I do not think those meet the standards yet.
They lack tests and coverage for example. Some are documented in non English.
Others are already in the list pretty much as current de-facto standard. It would need a good reason to add one of the same meaning here.

**Comment by dereuromark** [comment]
Thank you though for reaching out, and we can sure look into this again in the future.
Keep up the good work and let us know if you find any of those then useful for everyone else and not existing in the list yet in a similar way.
