### ISSUE TITLE
PSR-15 for Cake3

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/awesome-cakephp#320]
Cake 4 ships with PSR15 out of the box.
Should we recommend
https://github.com/kaz29/cakephp-psr15/blob/master/src/Middleware/PsrMiddleware.php
as Support for it in Cake 3?

Might help people upgrading easier if they can use certain ones via this shim?

**Comment by ADmad** [comment]
Shims like this won't work if a "double pass" middleware incorrectly modified the response instance before calling `$next()`. For e.g. cakehp/authentication 1.x's middleware does that.

So I would rather we don't suggest using such a shim.
