### ISSUE TITLE
CakePHP 4

### ISSUE THREAD

**Issue by sharkooon** [FriendsOfCake/awesome-cakephp#335]
Why is there no branch yet for cakephp 4?
There is a wiki page https://github.com/FriendsOfCake/awesome-cakephp/wiki/4.x-upgraded-ones .. but why a wiki page and not a branch? I'm confused.

**Comment by ADmad** [comment]
I take it you didn't read the readme of current master branch.

> Plugins with the "strawberry" icon have CakePHP 4 compatible release too.
