### ISSUE TITLE
awesome validation CI

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/awesome-cakephp#389]
this varci is not too helpful for specific issues

I ran a more specific validation tool

> Not a "cakephp-plugin": NewRelic (https://github.com/brunitto/cakephp-new-relic)
Not a "cakephp-plugin": PaypalWPP (https://github.com/cpierce/paypal-wpp)

We could ask the authors here to check in

It also checks if a license is available, and we can add more.

Is there a way to give me maintainer access to this repo?
So I can set up a webhook to this CI system for new PRs?

**Comment by ADmad** [comment]
Done
