### ISSUE TITLE
regarding security

### ISSUE THREAD

**Issue by Jeewakak** [FriendsOfCake/awesome-cakephp#401]
hi,
I am fascinated by your framework and support. as an organisation, you all support cake PHP.  I am a beginner to the backend and I see using the plugins ease coding stress.  

My question is how secure is plugins? or auto-generated codes. if I use auto-generate code or plugin will my e-commerce secure? 

this is very important for me. please answer. for example as an authentication plugin given by the organisation I believe it has to be secure. whereas other PHP frameworks mentioning authentication developed by this person rather than the organisation. 

will wait for reply

**Comment by dereuromark** [comment]
This is an awesome list, not a forum/chat.

**Comment by cnizzardini** [comment]
@Jeewakak try
https://discourse.cakephp.org/
https://www.reddit.com/r/cakephp/
