### ISSUE TITLE
CakePHP 5: Removal of CakePHP <= 3 ones

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/awesome-cakephp#411]
CakePHP 5 is coming closer
With this I urge everyone that has plugins on that list - or uses them and wants to support them - to upgrade them to CakePHP 4+ now.

With the release of 5, all non 4+ ones will be removed from master list.
We might store them in a legacy sheet or alike.

We want to promote awesomeness, and that requires at least a basic maintance on those, to make sure they can be used by current CakePHP developers and apps.

Thank you!

**Comment by cnizzardini** [comment]
Move them to a legacy page. They are still useful for those on older versions.

**Comment by dereuromark** [comment]
No, but I urge all maintainers or users to already start due diligence on those plugins if possible.
The eco system is a bit less active lately, it seems.

**Comment by cnizzardini** [comment]
I'm actually in a weird holding pattern on some of my plugins that I'm adding PHP 8 support to. I could end up doing back-to-back major version releases if I support PHP 8, then another to handle changes in cake 5.

**Comment by dereuromark** [comment]
Thats usually the best approach. At this point 7.2...8.1 is recommended for Cake4, while Cake5 is 8.0+ anyways.
I personally already go 7.3+ for now with Cake4.2+, and with Cake4.4 even 7.4+ as well.

**Comment by saeideng** [comment]
we can keep 3.x until end of life it , then moving to `3.x` branch to archive 

- 3.x | 4.x | 5.x | [plugin ](https://github.com/) - plugin for ...
- 3.x | 4.x | 5.x | [plugin ](https://github.com/) - plugin for ...
- 3.x | 4.x | [plugin ](https://github.com/) - plugin for ...
- ~3.x | [plugin ](https://github.com/) - plugin for ...~

**Comment by dereuromark** [comment]
No, I would prefer if we have only one major behind on Master. Bad enough as it is :)

**Comment by dereuromark** [comment]
I pushed master to https://github.com/FriendsOfCake/awesome-cakephp/tree/cake3 now and will remove all non Cake4+ plugins/resources now

**Comment by dereuromark** [comment]
https://github.com/FriendsOfCake/awesome-cakephp/pull/419
