### ISSUE TITLE
Cake3 Upload plugin

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/awesome-cakephp#76]
I would like to submit my plugin to the list for Cake 3 in the Files section.

https://github.com/davidyell/CakePHP3-Proffer

It's another upload plugin, but deals with generation of thumbnails and allows customisation using the events system. It's currently in alpha, but I am hoping to release a v1.0.0 when Cake 3 releases.

**Comment by dereuromark** [comment]
Please open it as a PR :)
