### ISSUE TITLE
Please remove outdated link from your readme

### ISSUE THREAD

**Issue by motsmanish** [FriendsOfCake/awesome-cakephp#88]
Hi there,

This link http://cakephpcheatsheet.com/ in your 'CakePHP Reading and Listening' section is been listed for sale and does no have anything related to cake, please remove it.

Thanks.

**Comment by dereuromark** [comment]
You can also make a PR to remove it from master and 2.x.
But otherwise we take care of it. Thx for reporting it.

**Comment by dereuromark** [comment]
Resolved in both branches.
